basePath: /api/v1
definitions:
  model.CreateSinlgePlayerGameRequest:
    properties:
      player_name:
        type: string
    required:
    - player_name
    type: object
  model.MakeMoveSinglePlayerRequest:
    properties:
      game_id:
        type: string
      move:
        type: string
    required:
    - game_id
    - move
    type: object
  model.Singleplayer:
    properties:
      card_sum:
        type: integer
      deck_id:
        type: string
      drawn_cards:
        items:
          type: string
        type: array
      game_id:
        type: string
      moves:
        items:
          type: string
        type: array
      player_name:
        type: string
      result:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    name: Rodrigo
  description: Exemplo de API em Go + Gin com Swagger e integração externa.
  title: Weather API Template
  version: "1.0"
paths:
  /create-game:
    post:
      consumes:
      - application/json
      description: Cria e persiste um novo jogo no banco
      parameters:
      - description: Dados do jogo
        in: body
        name: game
        required: true
        schema:
          $ref: '#/definitions/model.CreateSinlgePlayerGameRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/model.Singleplayer'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Cria um novo jogo singleplayer
      tags:
      - games
  /deck/shuffle:
    get:
      description: Embaralha um novo baralho de cartas
      parameters:
      - description: 'Número de baralhos (default: 1)'
        in: query
        name: count
        type: integer
      responses:
        "200":
          description: Baralho embaralhado
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Embaralhar baralho
      tags:
      - deck
  /get-games:
    get:
      description: Retorna todos os registros de jogos
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Singleplayer'
            type: array
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Lista todos os jogos singleplayer
      tags:
      - games
  /make-move-singleplayer:
    post:
      consumes:
      - application/json
      description: Cria e persiste um novo jogo no banco
      parameters:
      - description: Dados do jogo
        in: body
        name: game
        required: true
        schema:
          $ref: '#/definitions/model.MakeMoveSinglePlayerRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/model.Singleplayer'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Cria um novo jogo singleplayer
      tags:
      - games
  /weather/current:
    get:
      description: Consulta a temperatura atual via Open-Meteo
      parameters:
      - description: Latitude
        in: query
        name: lat
        required: true
        type: number
      - description: Longitude
        in: query
        name: lon
        required: true
        type: number
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: number
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Temperatura atual
      tags:
      - weather
schemes:
- http
swagger: "2.0"
